sudo: required

language: php

addons:
  apt:
    packages:
    - libevent-dev

php:
  - nightly

matrix:
  # allow_failures:
  #  - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - travis/install-async.sh
  - # Disabled due to segfaults: travis/install-uv.sh
  - # Disabled due to segfaults: travis/install-ev.sh
  - travis/install-event.sh

  - composer update -n --prefer-dist

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show

script:
  # Run testNoMemoryLeak separately, as those are skipped with enabled coverage
  - php vendor/bin/phpunit --verbose --group memoryleak
  - phpdbg -qrr vendor/bin/phpunit --verbose --exclude-group memoryleak --coverage-php coverage/cov/main.cov
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - curl -OL https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - phpdbg -qrr coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - ./coveralls.phar

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: change
    on_failure: change
